const ip = 'https://legaltechmap.ru'
const apiRoute = '/api'
export const projectsEndPoint = `${ip}${apiRoute}/companies`
export const categoriesEndPoint = `${ip}${apiRoute}/categories`
export const requestsEndPoint = `${ip}${apiRoute}/requests`
export const requestsUpdateEndPoint = `${ip}${apiRoute}/requests/update`
export const imageSendEndPoint = `${ip}${apiRoute}/images`
export const imgEndPoint = `${ip}/img-cloning`
export const authEndPoint = `${ip}${apiRoute}/auth/login`
